# Sync fork branch with upstream

name: Sync Fork Branch with Upstream

on:
  schedule:
  - cron: "0 15 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: master
    - name: Sync
      run: |
        git checkout master
        git remote add upstream https://github.com/ms-iot/rpi-iotcore.git
        git fetch upstream
        git pull upstream master
        git push origin master
